name = "deco"
main = "apps/api/main.ts"
compatibility_date = "2025-10-30"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Environment variables
[vars]
ENVIRONMENT = "production"
VITE_USE_LOCAL_BACKEND = "false"

# Durable Objects - SQLite format (required for free plan)
[[durable_objects.bindings]]
name = "AIAGENT"
class_name = "AIAgent"
script_name = "deco-chat-api"

[[durable_objects.bindings]]
name = "TRIGGER"
class_name = "Trigger"
script_name = "deco-chat-api"

[[durable_objects.bindings]]
name = "WORKSPACE_DB"
class_name = "WorkspaceDatabase"
script_name = "deco-chat-api"

[[durable_objects.bindings]]
name = "BRANCH"
class_name = "Branch"
script_name = "deco-chat-api"

[[durable_objects.bindings]]
name = "BLOBS"
class_name = "Blobs"
script_name = "deco-chat-api"

# Define Durable Object classes with SQLite storage
[[migrations]]
tag = "v1"
new_sqlite_classes = ["AIAgent", "Trigger", "WorkspaceDatabase", "Branch", "Blobs"]

# Workflow bindings for knowledge base file processing
[[workflows]]
name = "kb-file-processor"
binding = "KB_FILE_PROCESSOR"
class_name = "KbFileProcessorWorkflow"

[[workflows]]
name = "workflow-runner"
binding = "WORKFLOW_RUNNER"
class_name = "WorkflowRunner"
