name = "deco-chat-api"
main = "src/index.ts"
compatibility_date = "2025-10-30"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# No build command needed - Wrangler compiles TypeScript automatically
