/**
 * Theme presets for the deco CMS theme editor
 *
 * Source: https://github.com/jnsahaj/tweakcn (Apache-2.0)
 * Copyright (c) jnsahaj and contributors
 * Licensed under the Apache License, Version 2.0
 *
 * Modifications: Adapted for deco CMS theme system with additional color variants
 */

import type { Theme } from "@deco/sdk";

export interface ThemePreset {
  id: string;
  name: string;
  colors: string[]; // Array of 3 colors for preview dots
  theme: Theme;
}

// Theme presets - make immutable for tree-shaking
export const THEME_PRESETS = [
  {
    id: "default",
    name: "Deco",
    colors: ["#333333", "#f7f7f7", "#8e8e8e"],
    theme: {
      variables: {
        "--background": "oklch(1 0 0)",
        "--foreground": "oklch(0.205 0 0)",
        "--card": "oklch(0.976 0 0)",
        "--card-foreground": "oklch(0.205 0 0)",
        "--popover": "oklch(1 0 0)",
        "--popover-foreground": "oklch(0.205 0 0)",
        "--primary": "oklch(0.8916 0.2037 118.17)",
        "--primary-foreground": "oklch(0.3266 0.0858 149.2)",
        "--secondary": "oklch(0.97 0 0)",
        "--secondary-foreground": "oklch(0.205 0 0)",
        "--muted": "oklch(0.97 0 0)",
        "--muted-foreground": "oklch(0.556 0 0)",
        "--accent": "oklch(0.97 0 0)",
        "--accent-foreground": "oklch(0.205 0 0)",
        "--destructive": "oklch(0.577 0.245 27.325)",
        "--destructive-foreground": "oklch(1 0 0)",
        "--success": "oklch(0.654 0.184 142)",
        "--success-foreground": "oklch(0.963 0.025 137)",
        "--warning": "oklch(0.877 0.184 99)",
        "--warning-foreground": "oklch(0.293 0.071 70)",
        "--border": "oklch(0.922 0 0)",
        "--input": "oklch(0.922 0 0)",
        "--ring": "oklch(0.268 0.007 34.298)",
        "--chart-1": "oklch(0.646 0.222 41.116)",
        "--chart-2": "oklch(0.6 0.118 184.704)",
        "--chart-3": "oklch(0.398 0.07 227.392)",
        "--chart-4": "oklch(0.828 0.189 84.429)",
        "--chart-5": "oklch(0.769 0.188 70.08)",
        "--sidebar": "oklch(1 0 0)",
        "--sidebar-foreground": "oklch(0.205 0 0)",
        "--sidebar-accent": "oklch(0.97 0 0)",
        "--sidebar-accent-foreground": "oklch(0.205 0 0)",
        "--sidebar-border": "oklch(0.922 0 0)",
        "--radius": "0.625rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    colors: ["#3b82f6", "#60a5fa", "#93c5fd"],
    theme: {
      variables: {
        "--background": "#ffffff",
        "--foreground": "#333333",
        "--card": "#ffffff",
        "--card-foreground": "#333333",
        "--popover": "#ffffff",
        "--popover-foreground": "#333333",
        "--primary": "#3b82f6",
        "--primary-foreground": "#ffffff",
        "--secondary": "#f3f4f6",
        "--secondary-foreground": "#4b5563",
        "--muted": "#f9fafb",
        "--muted-foreground": "#6b7280",
        "--accent": "#e0f2fe",
        "--accent-foreground": "#1e3a8a",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--border": "#e5e7eb",
        "--input": "#e5e7eb",
        "--sidebar": "#f9fafb",
        "--sidebar-foreground": "#333333",
        "--sidebar-accent": "#e0f2fe",
        "--sidebar-accent-foreground": "#1e3a8a",
        "--sidebar-border": "#e5e7eb",
      },
    },
  },
  {
    id: "twitter",
    name: "Twitter",
    colors: ["#1e9df1", "#7856ff", "#ff6c44"],
    theme: {
      variables: {
        "--background": "#ffffff",
        "--foreground": "#0f1419",
        "--card": "#f7f8f8",
        "--card-foreground": "#0f1419",
        "--popover": "#ffffff",
        "--popover-foreground": "#0f1419",
        "--primary": "#1e9df1",
        "--primary-foreground": "#ffffff",
        "--secondary": "#0f1419",
        "--secondary-foreground": "#ffffff",
        "--muted": "#E5E5E6",
        "--muted-foreground": "#0f1419",
        "--accent": "#E3ECF6",
        "--accent-foreground": "#1e9df1",
        "--destructive": "#f4212e",
        "--destructive-foreground": "#ffffff",
        "--border": "#e1eaef",
        "--input": "#f7f9fa",
        "--sidebar": "#f7f8f8",
        "--sidebar-foreground": "#0f1419",
        "--sidebar-accent": "#E3ECF6",
        "--sidebar-accent-foreground": "#1e9df1",
        "--sidebar-border": "#e1e8ed",
      },
    },
  },
  {
    id: "amethyst-haze",
    name: "Amethyst Haze",
    colors: ["#8a79ab", "#e6a5b8", "#77b8a1"],
    theme: {
      variables: {
        "--background": "#f8f7fa",
        "--foreground": "#3d3c4f",
        "--card": "#ffffff",
        "--card-foreground": "#3d3c4f",
        "--popover": "#ffffff",
        "--popover-foreground": "#3d3c4f",
        "--primary": "#8a79ab",
        "--primary-foreground": "#f8f7fa",
        "--secondary": "#dfd9ec",
        "--secondary-foreground": "#3d3c4f",
        "--muted": "#dcd9e3",
        "--muted-foreground": "#6b6880",
        "--accent": "#e6a5b8",
        "--accent-foreground": "#4b2e36",
        "--destructive": "#d95c5c",
        "--destructive-foreground": "#f8f7fa",
        "--border": "#cec9d9",
        "--input": "#eae7f0",
        "--sidebar": "#f1eff5",
        "--sidebar-foreground": "#3d3c4f",
        "--sidebar-accent": "#e6a5b8",
        "--sidebar-accent-foreground": "#4b2e36",
        "--sidebar-border": "#d7d2e0",
      },
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin",
    colors: ["#8839ef", "#04a5e5", "#40a02b"],
    theme: {
      variables: {
        "--background": "#eff1f5",
        "--foreground": "#4c4f69",
        "--card": "#ffffff",
        "--card-foreground": "#4c4f69",
        "--popover": "#ccd0da",
        "--popover-foreground": "#4c4f69",
        "--primary": "#8839ef",
        "--primary-foreground": "#ffffff",
        "--secondary": "#ccd0da",
        "--secondary-foreground": "#4c4f69",
        "--muted": "#dce0e8",
        "--muted-foreground": "#6c6f85",
        "--accent": "#04a5e5",
        "--accent-foreground": "#ffffff",
        "--destructive": "#d20f39",
        "--destructive-foreground": "#ffffff",
        "--border": "#bcc0cc",
        "--input": "#ccd0da",
        "--sidebar": "#e6e9ef",
        "--sidebar-foreground": "#4c4f69",
        "--sidebar-accent": "#04a5e5",
        "--sidebar-accent-foreground": "#ffffff",
        "--sidebar-border": "#bcc0cc",
      },
    },
  },
  {
    id: "kodama-grove",
    name: "Kodama Grove",
    colors: ["#84cc16", "#a3e635", "#bef264"],
    theme: {
      variables: {
        "--background": "#fbfff3",
        "--foreground": "#1a1a1a",
        "--card": "#f9fcf2",
        "--card-foreground": "#1a1a1a",
        "--popover": "#f9fcf2",
        "--popover-foreground": "#1a1a1a",
        "--primary": "#84cc16",
        "--primary-foreground": "#ffffff",
        "--secondary": "#e5f3c0",
        "--secondary-foreground": "#1a1a1a",
        "--muted": "#f2f7df",
        "--muted-foreground": "#5a6c3f",
        "--accent": "#e5f3c0",
        "--accent-foreground": "#1a1a1a",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--border": "#d9e8a3",
        "--input": "#e5f3c0",
        "--sidebar": "#f5fae6",
        "--sidebar-foreground": "#1a1a1a",
        "--sidebar-accent": "#e5f3c0",
        "--sidebar-accent-foreground": "#1a1a1a",
        "--sidebar-border": "#d9e8a3",
      },
    },
  },
  {
    id: "quantum-rose",
    name: "Quantum Rose",
    colors: ["#e11d48", "#be123c", "#9f1239"],
    theme: {
      variables: {
        "--background": "#fff0f3",
        "--foreground": "#1f1315",
        "--card": "#fff5f7",
        "--card-foreground": "#1f1315",
        "--popover": "#fff5f7",
        "--popover-foreground": "#1f1315",
        "--primary": "#e11d48",
        "--primary-foreground": "#ffffff",
        "--secondary": "#ffd6e0",
        "--secondary-foreground": "#1f1315",
        "--muted": "#ffe0e8",
        "--muted-foreground": "#6b4c52",
        "--accent": "#ffd6e0",
        "--accent-foreground": "#1f1315",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--border": "#ffc1d4",
        "--input": "#ffd6e0",
        "--sidebar": "#fff8fa",
        "--sidebar-foreground": "#1f1315",
        "--sidebar-accent": "#ffd6e0",
        "--sidebar-accent-foreground": "#1f1315",
        "--sidebar-border": "#ffc1d4",
      },
    },
  },
  {
    id: "elegant-luxury",
    name: "Elegant Luxury",
    colors: ["#d4af37", "#c99a2e", "#b8860b"],
    theme: {
      variables: {
        "--background": "#1c1917",
        "--foreground": "#f5f5f4",
        "--card": "#292524",
        "--card-foreground": "#f5f5f4",
        "--popover": "#292524",
        "--popover-foreground": "#f5f5f4",
        "--primary": "#d4af37",
        "--primary-foreground": "#1c1917",
        "--secondary": "#44403c",
        "--secondary-foreground": "#e7e5e4",
        "--muted": "#292524",
        "--muted-foreground": "#a8a29e",
        "--accent": "#44403c",
        "--accent-foreground": "#e7e5e4",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--border": "#44403c",
        "--input": "#44403c",
        "--sidebar": "#1c1917",
        "--sidebar-foreground": "#f5f5f4",
        "--sidebar-accent": "#44403c",
        "--sidebar-accent-foreground": "#e7e5e4",
        "--sidebar-border": "#44403c",
      },
    },
  },
  {
    id: "mocha-mousse",
    name: "Mocha Mousse",
    colors: ["#A37764", "#8A655A", "#C39E88"],
    theme: {
      variables: {
        "--background": "#F1F0E5",
        "--foreground": "#56453F",
        "--card": "#F1F0E5",
        "--card-foreground": "#56453F",
        "--popover": "#FFFFFF",
        "--popover-foreground": "#56453F",
        "--primary": "#A37764",
        "--primary-foreground": "#FFFFFF",
        "--secondary": "#BAAB92",
        "--secondary-foreground": "#ffffff",
        "--muted": "#E4C7B8",
        "--muted-foreground": "#8A655A",
        "--accent": "#E4C7B8",
        "--accent-foreground": "#56453F",
        "--destructive": "#1f1a17",
        "--destructive-foreground": "#FFFFFF",
        "--border": "#BAAB92",
        "--input": "#BAAB92",
        "--sidebar": "#ebd6cb",
        "--sidebar-foreground": "#56453F",
        "--sidebar-accent": "#C39E88",
        "--sidebar-accent-foreground": "#ffffff",
        "--sidebar-border": "#A28777",
      },
    },
  },
  {
    id: "notebook",
    name: "Notebook",
    colors: ["#606060", "#dedede", "#f3eac8"],
    theme: {
      variables: {
        "--background": "#f9f9f9",
        "--foreground": "#3a3a3a",
        "--card": "#ffffff",
        "--card-foreground": "#3a3a3a",
        "--popover": "#ffffff",
        "--popover-foreground": "#3a3a3a",
        "--primary": "#606060",
        "--primary-foreground": "#f0f0f0",
        "--secondary": "#dedede",
        "--secondary-foreground": "#3a3a3a",
        "--muted": "#e3e3e3",
        "--muted-foreground": "#505050",
        "--accent": "#f3eac8",
        "--accent-foreground": "#5d4037",
        "--destructive": "#c87a7a",
        "--destructive-foreground": "#ffffff",
        "--border": "#747272",
        "--input": "#ffffff",
        "--sidebar": "#f0f0f0",
        "--sidebar-foreground": "#3a3a3a",
        "--sidebar-accent": "#f3eac8",
        "--sidebar-accent-foreground": "#5d4037",
        "--sidebar-border": "#c0c0c0",
      },
    },
  },
  {
    id: "graphite",
    name: "Graphite",
    colors: ["#606060", "#909090", "#c0c0c0"],
    theme: {
      variables: {
        "--background": "#f0f0f0",
        "--foreground": "#333333",
        "--card": "#f5f5f5",
        "--card-foreground": "#333333",
        "--popover": "#f5f5f5",
        "--popover-foreground": "#333333",
        "--primary": "#606060",
        "--primary-foreground": "#ffffff",
        "--secondary": "#e0e0e0",
        "--secondary-foreground": "#333333",
        "--muted": "#d9d9d9",
        "--muted-foreground": "#666666",
        "--accent": "#c0c0c0",
        "--accent-foreground": "#333333",
        "--destructive": "#cc3333",
        "--destructive-foreground": "#ffffff",
        "--border": "#d0d0d0",
        "--input": "#e0e0e0",
        "--sidebar": "#eaeaea",
        "--sidebar-foreground": "#333333",
        "--sidebar-accent": "#c0c0c0",
        "--sidebar-accent-foreground": "#333333",
        "--sidebar-border": "#d0d0d0",
      },
    },
  },
  {
    id: "cosmic-night",
    name: "Cosmic Night",
    colors: ["#a855f7", "#c084fc", "#e9d5ff"],
    theme: {
      variables: {
        "--background": "#0f0a1f",
        "--foreground": "#e0d7f5",
        "--card": "#1a1429",
        "--card-foreground": "#e0d7f5",
        "--popover": "#1a1429",
        "--popover-foreground": "#e0d7f5",
        "--primary": "#a855f7",
        "--primary-foreground": "#ffffff",
        "--secondary": "#312647",
        "--secondary-foreground": "#e0d7f5",
        "--muted": "#1f1833",
        "--muted-foreground": "#9888c7",
        "--accent": "#2d2348",
        "--accent-foreground": "#c084fc",
        "--destructive": "#f43f5e",
        "--destructive-foreground": "#ffffff",
        "--border": "#372a54",
        "--input": "#261c40",
        "--sidebar": "#0d0819",
        "--sidebar-foreground": "#e0d7f5",
        "--sidebar-accent": "#2d2348",
        "--sidebar-accent-foreground": "#c084fc",
        "--sidebar-border": "#372a54",
      },
    },
  },
  {
    id: "nature",
    name: "Nature",
    colors: ["#10b981", "#34d399", "#6ee7b7"],
    theme: {
      variables: {
        "--background": "#f0fdf4",
        "--foreground": "#14532d",
        "--card": "#f7fef9",
        "--card-foreground": "#14532d",
        "--popover": "#f7fef9",
        "--popover-foreground": "#14532d",
        "--primary": "#10b981",
        "--primary-foreground": "#ffffff",
        "--secondary": "#d1fae5",
        "--secondary-foreground": "#14532d",
        "--muted": "#dcfce7",
        "--muted-foreground": "#166534",
        "--accent": "#d1fae5",
        "--accent-foreground": "#14532d",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--border": "#bbf7d0",
        "--input": "#d1fae5",
        "--sidebar": "#ecfdf5",
        "--sidebar-foreground": "#14532d",
        "--sidebar-accent": "#d1fae5",
        "--sidebar-accent-foreground": "#14532d",
        "--sidebar-border": "#bbf7d0",
      },
    },
  },
  {
    id: "amber-minimal",
    name: "Amber Minimal",
    colors: ["#f59e0b", "#fbbf24", "#fcd34d"],
    theme: {
      variables: {
        "--background": "#fffbeb",
        "--foreground": "#78350f",
        "--card": "#fffef7",
        "--card-foreground": "#78350f",
        "--popover": "#fffef7",
        "--popover-foreground": "#78350f",
        "--primary": "#f59e0b",
        "--primary-foreground": "#ffffff",
        "--secondary": "#fef3c7",
        "--secondary-foreground": "#78350f",
        "--muted": "#fef9c3",
        "--muted-foreground": "#a16207",
        "--accent": "#fef3c7",
        "--accent-foreground": "#78350f",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--border": "#fde68a",
        "--input": "#fef3c7",
        "--sidebar": "#fffaeb",
        "--sidebar-foreground": "#78350f",
        "--sidebar-accent": "#fef3c7",
        "--sidebar-accent-foreground": "#78350f",
        "--sidebar-border": "#fde68a",
      },
    },
  },
  {
    id: "solar-dusk",
    name: "Solar Dusk",
    colors: ["#ea580c", "#f97316", "#fb923c"],
    theme: {
      variables: {
        "--background": "#fff7ed",
        "--foreground": "#7c2d12",
        "--card": "#fffaf5",
        "--card-foreground": "#7c2d12",
        "--popover": "#fffaf5",
        "--popover-foreground": "#7c2d12",
        "--primary": "#ea580c",
        "--primary-foreground": "#ffffff",
        "--secondary": "#ffedd5",
        "--secondary-foreground": "#7c2d12",
        "--muted": "#fed7aa",
        "--muted-foreground": "#9a3412",
        "--accent": "#ffedd5",
        "--accent-foreground": "#7c2d12",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--border": "#fdba74",
        "--input": "#ffedd5",
        "--sidebar": "#fff4ed",
        "--sidebar-foreground": "#7c2d12",
        "--sidebar-accent": "#ffedd5",
        "--sidebar-accent-foreground": "#7c2d12",
        "--sidebar-border": "#fdba74",
      },
    },
  },
  {
    id: "perpetuity",
    name: "Perpetuity",
    colors: ["#06b6d4", "#0891b2", "#0e7490"],
    theme: {
      variables: {
        "--background": "#ecfeff",
        "--foreground": "#164e63",
        "--card": "#f7feff",
        "--card-foreground": "#164e63",
        "--popover": "#f7feff",
        "--popover-foreground": "#164e63",
        "--primary": "#06b6d4",
        "--primary-foreground": "#ffffff",
        "--secondary": "#cffafe",
        "--secondary-foreground": "#164e63",
        "--muted": "#e0f2fe",
        "--muted-foreground": "#155e75",
        "--accent": "#cffafe",
        "--accent-foreground": "#164e63",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--border": "#a5f3fc",
        "--input": "#cffafe",
        "--sidebar": "#f0fdff",
        "--sidebar-foreground": "#164e63",
        "--sidebar-accent": "#cffafe",
        "--sidebar-accent-foreground": "#164e63",
        "--sidebar-border": "#a5f3fc",
      },
    },
  },
  {
    id: "tangerine",
    name: "Tangerine",
    colors: ["#f97316", "#fb923c", "#fdba74"],
    theme: {
      variables: {
        "--background": "#fff7ed",
        "--foreground": "#7c2d12",
        "--card": "#fffaf5",
        "--card-foreground": "#7c2d12",
        "--popover": "#fffaf5",
        "--popover-foreground": "#7c2d12",
        "--primary": "#f97316",
        "--primary-foreground": "#ffffff",
        "--secondary": "#ffedd5",
        "--secondary-foreground": "#7c2d12",
        "--muted": "#fed7aa",
        "--muted-foreground": "#9a3412",
        "--accent": "#ffedd5",
        "--accent-foreground": "#7c2d12",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--border": "#fdba74",
        "--input": "#ffedd5",
        "--sidebar": "#fff4ed",
        "--sidebar-foreground": "#7c2d12",
        "--sidebar-accent": "#ffedd5",
        "--sidebar-accent-foreground": "#7c2d12",
        "--sidebar-border": "#fdba74",
      },
    },
  },
  {
    id: "bold-tech",
    name: "Bold Tech",
    colors: ["#7c3aed", "#8b5cf6", "#a78bfa"],
    theme: {
      variables: {
        "--background": "#0f0a1a",
        "--foreground": "#e9e3ff",
        "--card": "#1a1329",
        "--card-foreground": "#e9e3ff",
        "--popover": "#1a1329",
        "--popover-foreground": "#e9e3ff",
        "--primary": "#7c3aed",
        "--primary-foreground": "#ffffff",
        "--secondary": "#2a1f3d",
        "--secondary-foreground": "#e9e3ff",
        "--muted": "#1f1833",
        "--muted-foreground": "#a995d5",
        "--accent": "#2d2348",
        "--accent-foreground": "#a78bfa",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--border": "#372a54",
        "--input": "#261c40",
        "--sidebar": "#0d0819",
        "--sidebar-foreground": "#e9e3ff",
        "--sidebar-accent": "#2d2348",
        "--sidebar-accent-foreground": "#a78bfa",
        "--sidebar-border": "#372a54",
      },
    },
  },
  {
    id: "supabase",
    name: "Supabase",
    colors: ["#3ecf8e", "#10b981", "#06b6d4"],
    theme: {
      variables: {
        "--background": "#0f1729",
        "--foreground": "#f5f5f5",
        "--card": "#1a2332",
        "--card-foreground": "#f5f5f5",
        "--popover": "#1a2332",
        "--popover-foreground": "#f5f5f5",
        "--primary": "#3ecf8e",
        "--primary-foreground": "#0f1729",
        "--secondary": "#1e293b",
        "--secondary-foreground": "#f5f5f5",
        "--muted": "#1e293b",
        "--muted-foreground": "#94a3b8",
        "--accent": "#1e293b",
        "--accent-foreground": "#3ecf8e",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--border": "#334155",
        "--input": "#1e293b",
        "--sidebar": "#0d1321",
        "--sidebar-foreground": "#f5f5f5",
        "--sidebar-accent": "#1e293b",
        "--sidebar-accent-foreground": "#3ecf8e",
        "--sidebar-border": "#334155",
      },
    },
  },
  {
    id: "claymorphism",
    name: "Claymorphism",
    colors: ["#6366f1", "#8b5cf6", "#ec4899"],
    theme: {
      variables: {
        "--background": "#f3f4f6",
        "--foreground": "#1f2937",
        "--card": "#ffffff",
        "--card-foreground": "#1f2937",
        "--popover": "#ffffff",
        "--popover-foreground": "#1f2937",
        "--primary": "#6366f1",
        "--primary-foreground": "#ffffff",
        "--secondary": "#e5e7eb",
        "--secondary-foreground": "#1f2937",
        "--muted": "#f9fafb",
        "--muted-foreground": "#6b7280",
        "--accent": "#f3e8ff",
        "--accent-foreground": "#6b21a8",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--border": "#d1d5db",
        "--input": "#e5e7eb",
        "--sidebar": "#f9fafb",
        "--sidebar-foreground": "#1f2937",
        "--sidebar-accent": "#f3e8ff",
        "--sidebar-accent-foreground": "#6b21a8",
        "--sidebar-border": "#d1d5db",
      },
    },
  },
  {
    id: "neo-brutalism",
    name: "Neo Brutalism",
    colors: ["#ff6b6b", "#4ecdc4", "#ffe66d"],
    theme: {
      variables: {
        "--background": "#ffffff",
        "--foreground": "#000000",
        "--card": "#ffffff",
        "--card-foreground": "#000000",
        "--popover": "#ffffff",
        "--popover-foreground": "#000000",
        "--primary": "#ff6b6b",
        "--primary-foreground": "#ffffff",
        "--secondary": "#4ecdc4",
        "--secondary-foreground": "#000000",
        "--muted": "#f5f5f5",
        "--muted-foreground": "#666666",
        "--accent": "#ffe66d",
        "--accent-foreground": "#000000",
        "--destructive": "#ff6b6b",
        "--destructive-foreground": "#ffffff",
        "--border": "#000000",
        "--input": "#ffffff",
        "--sidebar": "#f5f5f5",
        "--sidebar-foreground": "#000000",
        "--sidebar-accent": "#ffe66d",
        "--sidebar-accent-foreground": "#000000",
        "--sidebar-border": "#000000",
      },
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    colors: ["#ff00ff", "#00ffff", "#ff0099"],
    theme: {
      variables: {
        "--background": "#0a0a1a",
        "--foreground": "#e0e0ff",
        "--card": "#151530",
        "--card-foreground": "#e0e0ff",
        "--popover": "#151530",
        "--popover-foreground": "#e0e0ff",
        "--primary": "#ff00ff",
        "--primary-foreground": "#26122b",
        "--secondary": "#00ffff",
        "--secondary-foreground": "#000000",
        "--muted": "#1a1a2e",
        "--muted-foreground": "#a0a0d0",
        "--accent": "#ff0099",
        "--accent-foreground": "#ffffff",
        "--destructive": "#ff3366",
        "--destructive-foreground": "#ffffff",
        "--border": "#3a3a5a",
        "--input": "#1a1a3a",
        "--sidebar": "#080810",
        "--sidebar-foreground": "#e0e0ff",
        "--sidebar-accent": "#ff0099",
        "--sidebar-accent-foreground": "#ffffff",
        "--sidebar-border": "#3a3a5a",
      },
    },
  },
  {
    id: "pastel-dreams",
    name: "Pastel Dreams",
    colors: ["#c7b3e5", "#b3d4e5", "#e5b3d4"],
    theme: {
      variables: {
        "--background": "#faf8ff",
        "--foreground": "#4a3f5c",
        "--card": "#ffffff",
        "--card-foreground": "#4a3f5c",
        "--popover": "#ffffff",
        "--popover-foreground": "#4a3f5c",
        "--primary": "#c7b3e5",
        "--primary-foreground": "#ffffff",
        "--secondary": "#e8dff5",
        "--secondary-foreground": "#4a3f5c",
        "--muted": "#f3eeff",
        "--muted-foreground": "#6b5f7e",
        "--accent": "#e5b3d4",
        "--accent-foreground": "#5c3f52",
        "--destructive": "#e57373",
        "--destructive-foreground": "#ffffff",
        "--border": "#d9c7ed",
        "--input": "#e8dff5",
        "--sidebar": "#f8f5ff",
        "--sidebar-foreground": "#4a3f5c",
        "--sidebar-accent": "#e5b3d4",
        "--sidebar-accent-foreground": "#5c3f52",
        "--sidebar-border": "#d9c7ed",
      },
    },
  },
  {
    id: "doom-64",
    name: "Doom 64",
    colors: ["#b71c1c", "#556b2f", "#4682b4"],
    theme: {
      variables: {
        "--background": "#cccccc",
        "--foreground": "#1f1f1f",
        "--card": "#b0b0b0",
        "--card-foreground": "#1f1f1f",
        "--popover": "#b0b0b0",
        "--popover-foreground": "#1f1f1f",
        "--primary": "#b71c1c",
        "--primary-foreground": "#ffffff",
        "--secondary": "#556b2f",
        "--secondary-foreground": "#ffffff",
        "--muted": "#b8b8b8",
        "--muted-foreground": "#4a4a4a",
        "--accent": "#4682b4",
        "--accent-foreground": "#ffffff",
        "--destructive": "#ff6f00",
        "--destructive-foreground": "#000000",
        "--border": "#505050",
        "--input": "#505050",
        "--sidebar": "#b0b0b0",
        "--sidebar-foreground": "#1f1f1f",
        "--sidebar-accent": "#4682b4",
        "--sidebar-accent-foreground": "#ffffff",
        "--sidebar-border": "#505050",
      },
    },
  },
  {
    id: "violet-bloom",
    name: "Violet Bloom",
    colors: ["#7033ff", "#4ac885", "#fd822b"],
    theme: {
      variables: {
        "--background": "#fdfdfd",
        "--foreground": "#000000",
        "--card": "#fdfdfd",
        "--card-foreground": "#000000",
        "--popover": "#fcfcfc",
        "--popover-foreground": "#000000",
        "--primary": "#7033ff",
        "--primary-foreground": "#ffffff",
        "--secondary": "#edf0f4",
        "--secondary-foreground": "#080808",
        "--muted": "#f5f5f5",
        "--muted-foreground": "#525252",
        "--accent": "#e2ebff",
        "--accent-foreground": "#1e69dc",
        "--destructive": "#e54b4f",
        "--destructive-foreground": "#ffffff",
        "--border": "#e7e7ee",
        "--input": "#ebebeb",
        "--sidebar": "#f5f8fb",
        "--sidebar-foreground": "#000000",
        "--sidebar-accent": "#ebebeb",
        "--sidebar-accent-foreground": "#000000",
        "--sidebar-border": "#ebebeb",
      },
    },
  },
  {
    id: "bubblegum",
    name: "Bubblegum",
    colors: ["#d04f99", "#84d2e2", "#fbe2a7"],
    theme: {
      variables: {
        "--background": "#f6e6ee",
        "--foreground": "#5b5b5b",
        "--card": "#fdedc9",
        "--card-foreground": "#5b5b5b",
        "--popover": "#ffffff",
        "--popover-foreground": "#5b5b5b",
        "--primary": "#d04f99",
        "--primary-foreground": "#ffffff",
        "--secondary": "#8acfd1",
        "--secondary-foreground": "#333333",
        "--muted": "#b2e1eb",
        "--muted-foreground": "#7a7a7a",
        "--accent": "#fbe2a7",
        "--accent-foreground": "#333333",
        "--destructive": "#f96f70",
        "--destructive-foreground": "#ffffff",
        "--border": "#d04f99",
        "--input": "#e4e4e4",
        "--sidebar": "#f8d8ea",
        "--sidebar-foreground": "#333333",
        "--sidebar-accent": "#f9a8d4",
        "--sidebar-accent-foreground": "#333333",
        "--sidebar-border": "#f3e8ff",
      },
    },
  },
  {
    id: "clean-slate",
    name: "Clean Slate",
    colors: ["#64748b", "#94a3b8", "#cbd5e1"],
    theme: {
      variables: {
        "--background": "#f8fafc",
        "--foreground": "#0f172a",
        "--card": "#ffffff",
        "--card-foreground": "#0f172a",
        "--popover": "#ffffff",
        "--popover-foreground": "#0f172a",
        "--primary": "#64748b",
        "--primary-foreground": "#ffffff",
        "--secondary": "#f1f5f9",
        "--secondary-foreground": "#0f172a",
        "--muted": "#f1f5f9",
        "--muted-foreground": "#64748b",
        "--accent": "#e2e8f0",
        "--accent-foreground": "#1e293b",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--border": "#e2e8f0",
        "--input": "#f1f5f9",
        "--sidebar": "#f8fafc",
        "--sidebar-foreground": "#0f172a",
        "--sidebar-accent": "#e2e8f0",
        "--sidebar-accent-foreground": "#1e293b",
        "--sidebar-border": "#e2e8f0",
      },
    },
  },
  {
    id: "retro-arcade",
    name: "Retro Arcade",
    colors: ["#ff6b6b", "#4ecdc4", "#ffe66d"],
    theme: {
      variables: {
        "--background": "#1a1a2e",
        "--foreground": "#eee",
        "--card": "#16213e",
        "--card-foreground": "#eee",
        "--popover": "#0f3460",
        "--popover-foreground": "#eee",
        "--primary": "#ff6b6b",
        "--primary-foreground": "#ffffff",
        "--secondary": "#4ecdc4",
        "--secondary-foreground": "#1a1a2e",
        "--muted": "#0f3460",
        "--muted-foreground": "#94a1b2",
        "--accent": "#ffe66d",
        "--accent-foreground": "#1a1a2e",
        "--destructive": "#e74c3c",
        "--destructive-foreground": "#ffffff",
        "--border": "#334e68",
        "--input": "#0f3460",
        "--sidebar": "#16213e",
        "--sidebar-foreground": "#eee",
        "--sidebar-accent": "#ffe66d",
        "--sidebar-accent-foreground": "#1a1a2e",
        "--sidebar-border": "#334e68",
      },
    },
  },
] as const satisfies ReadonlyArray<ThemePreset>;
